version: 1
disable_existing_loggers: true
formatters:
  default:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  uvicorn:
    "()": "uvicorn.logging.DefaultFormatter"
    format: "%(levelprefix)s %(message)s"
handlers:
  uvicorn_log:
    class: logging.FileHandler
    filename: /var/log/dnsscan/uvicorn.log
    formatter: default
    level: INFO
  sql_log:
    class: logging.FileHandler
    filename: /var/log/dnsscan/database.log
    formatter: default
    level: INFO
  console:
    class: logging.StreamHandler
    formatter: uvicorn
    level: INFO
loggers:
  uvicorn:
    handlers: ["uvicorn_log"]
    level: INFO
    propagate: false
  uvicorn.error:
    level: INFO
  uvicorn.access:
    handlers: ["uvicorn_log"]
    level: INFO
    propagate: false
  sqlalchemy.engine:
    handlers: ["sql_log"]
    level: INFO
    propagate: false
root:
  handlers: ["console"]
  level: WARNING
